markdown: redcarpet
pygments: true
permalink: /:title

url:

redcarpet:
  extensions: [strikethrough]

authors:
  clement:
    name: Clément
    twitter: clemkeirua
  christophe:
    name: christophe
    twitter: churpeau
  matthieu:
    name: Matthieu
    twitter: maffpool

disqus: tech-evaneos
