markdown: redcarpet
pygments: true
permalink: /:title
safe: false

url:

redcarpet:
  extensions: [strikethrough]

authors:
  clement:
    name: Clément
    twitter: clemkeirua
  christophe:
    name: christophe
    twitter: churpeau

disqus: tech-evaneos
