markdown: redcarpet
pygments: true
permalink: /:title-:year-:month-:day/
safe: false

url:

redcarpet:
  extensions: [strikethrough]

authors:
  clement:
    name: Clément
    twitter: clemkeirua
  christophe:
    name: christophe
    twitter: churpeau
  matthieu:
    name: Matthieu
    twitter: maffpool
  tilap:
    name: Tilap
    twitter: jlavinh

disqus: tech-evaneos
